steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sodium-dynamo-292520/book-store', '.']
images: ['gcr.io/sodium-dynamo-292520/book-store']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'kubectl'
  args: ['apply', '-f', 'k8s/book-store-ns.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=prod'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'kubectl'
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=prod'
