apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata: 
  name: book-store-ingress
  namespace: backend
spec:
  rules:
  - host: book-store.shahargn.com
    http:
      paths:  
      - backend:
          serviceName: book-store-internal-service
          servicePort: 8000
