apiVersion: apps/v1
kind: Deployment
metadata: 
  name: book-store-deployment
  namespace: backend
  labels:
    app: books-store
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: book-store
  template:
    metadata:
      labels:
        app: book-store
    spec:
      containers:
      - name: book-store
        image: IMAGE_VAR
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "34.78.100.176"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "9Gmj2mqhdDO4xdPd"   
        resources:
          requests:
            cpu: 80m
          limits:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata: 
  name: book-store-internal-service
  namespace: backend
spec:
  selector:
    app: book-store
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
