name: CI-workflow to run test on the code

on: [push]

jobs:
  run-tests-on-code:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install pipenv 
      run: pip install pipenv && pipenv shell

    - name: going into env shell
      run: pipenv shell

    - name:  installing dependencys
      run: pipenv install --dev --ignore-pipfile
      
    - name: run the linter
      run: pycodestyle .

    - name: run the tests
      run: python -m unitest 