name: CI-workflow
description: run some test on every push on the repo

on: [push]

jobs:
  build:

  runs-on: ubuntu-latest

    steps:
    - uses: action/checkout@v2

    -name: install pipenv and going into env shell
      run: pip install pipenv && pipenv shell

    -name:  installing dependencys
      run: pipenv install --dev --ignore-pipfile
      
    -name: run the linter
      run: pycodestyle .

    -name: run the tests
      run: python -m unitest 